### DISCUSSION TITLE
Why not use the standard Birdnet-Analyzer?

### DISCUSSION THREAD

**Discussion by fightforlife** [mmcc-xx/BirdCAGE#2] [Ideas]
Just a question: Why are you not using the standard Birdnet-Analyzer image?

The standard server.py and standard Dockerfile seems to be working fine for analysis. BUt the backend cannot interpret the answer.
Using the standard image would reduce dependencies and would make deployment much easier.

[2023-05-19 12:03:56,339: INFO/MainProcess] Task app.stream_processing.analyze_recordings[3b79922b-1d50-4197-a63f-f835521d2488] received
[2023-05-19 12:03:56,342: WARNING/ForkPoolWorker-2] Requesting analysis for /app/../tmp/f7e89c0660d74cbd8437e122a360f964.wav
[2023-05-19 12:03:56,674: WARNING/ForkPoolWorker-2] {'msg': 'success', 'results': [['Icterus spurius_Orchard Oriole', 0.1562], ['Mimus polyglottos_Northern Mockingbird', 0.0946], ['Toxostoma rufum_Brown Thrasher', 0.063], ['Colinus virginianus_Northern Bobwhite', 0.0576], ['Chondestes grammacus_Lark Sparrow', 0.0481]]}
[2023-05-19 12:03:56,677: WARNING/ForkPoolWorker-2] Time interval: ['Icterus spurius_Orchard Oriole', 0.1562]
[2023-05-19 12:03:56,679: ERROR/ForkPoolWorker-2] Task app.stream_processing.analyze_recordings[3b79922b-1d50-4197-a63f-f835521d2488] raised unexpected: TypeError('list indices must be integers or slices, not list')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/__init__.py", line 60, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/stream_processing.py", line 229, in analyze_recordings
    check_results(analysis['results'], file_path, recording_metadata, preferences)
  File "/app/stream_processing.py", line 116, in check_results
    interval_results = results[time_interval]
TypeError: list indices must be integers or slices, not list

**Comment by mmcc-xx** [comment]
I had to make two changes to the Birdnet-Analyzer image...
1) I had to change their dockerfile to run server.py. By default it runs analyze.py which is less useful - it start up, runs, and shuts down for whatever it is passed. That would be a lot of container starting and stopping.
2) The output of their server.py didn't include the interval in which the song was detected, so I changed their server.py to include it.

I opened an issue on their repo asking them to make these changes. They marked it as an enhancement. I hope they implement it!

**Reply by fightforlife** [reply]
Thanks for the info! Some ideas from my side (how I solved this for now):

1. You can overwrite the standard command in docker (compose). Just specify ``command: server_birdcage.py`` when running the container and the standard analyze.py command will be overwritten.

2. You could create a PR where your server.py is included as a secondary variant, like server_birdcage.py. (ofcourse only when changing the original one is denied)

**Reply by mmcc-xx** [reply]
What’s a PR?

It certainly would be nice to be able to have one docker-compose file that did every. However I don’t think they push their image to docker hub. I may be mistaken and will check that.

**Reply by fightforlife** [reply]
PR is a pull request to change something in the source.

I got it working in one docker compose. Just a test nothing official.

```
version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  analyzer:
    image: ghcr.io/fightforlife/birdnet-analyzer:main
    ports:
      - 7667:7667
    command: server_birdcage.py --port 7667 --locale de

  backend:
    image: mmcc73/birdcage_backend:latest
    ports:
      - 7007:7007
    environment:
      DATABASE_FILE: /db/birdcage.db
      API_SERVER_PORT: 7007
      TEMP_DIR_NAME: tmp
      ANALYZE_SERVER: 192.168.1.4
      ANALYZE_PORT: 7667
      DETECTION_DIR_NAME: detections
      CORS_ORIGINS: http://192.168.1.4:7008
      REDIS_SERVER: redis
      REDIS_PORT: 6379
    volumes:
      - tmp:/tmp
      - detections:/detections
      - db:/db
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - redis

  frontend:
    image: mmcc73/birdcage_frontend:latest
    ports:
      - 7008:7008
    environment:
      API_SERVER_URL: http://192.168.1.4:7007
      WEBUI_PORT: 7008
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - backend

volumes:
  tmp:
  detections:
  db:
```
