### DISCUSSION TITLE
Write /tmp files to tmpfs

### DISCUSSION THREAD

**Discussion by Phaeton** [mmcc-xx/BirdCAGE#5] [Ideas]
It would be good to minimize the writes to disk, by writing the `/tmp` files to ram instead. I have tested the below for a few hours now without any issues. The key here is the `tmpfs:` block. I also added `/var/log`. If this works well for others, I can submit a PR to update the default `docker-compose.yml` config.

```  
  birdcage_backend:
    image: "mmcc73/birdcage_backend:latest"
    ports:
      - "7007:7007"
    environment:
      DATABASE_FILE: /db/birdcage.db
      API_SERVER_PORT: 7007
      TEMP_DIR_NAME: tmp
      ANALYZE_SERVER: 192.168.1.75
      ANALYZE_PORT: 7667
      DETECTION_DIR_NAME: detections
      CORS_ORIGINS: http://192.168.1.75:7008
      REDIS_SERVER: redis
      REDIS_PORT: 6379
    tmpfs:
      - /tmp:exec,size=16M
      - /var/log
    volumes:
#      - "./birdcage/tmp:/tmp"
      - "./birdcage/detections:/detections"
      - "./birdcage/db:/db"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    depends_on:
      - redis
```
