### ISSUE TITLE
No space left on device ffmpeg?

### ISSUE THREAD

**Issue by yetdog** [mmcc-xx/BirdCAGE#15]
A couple of minutes after starting the app:

```
birdcage-birdcage_backend-1   | [2023-05-23 06:53:53,189: INFO/MainProcess] Task app.stream_processing.record_stream[e96a1804-b4f7-49f0-9533-498501bbf974] received
birdcage-birdcage_backend-1   | [2023-05-23 06:53:53,196: INFO/MainProcess] Task app.stream_processing.record_stream[72ccb0d9-d551-4aef-8282-28c09023effb] received
birdcage-birdcage_backend-1   | [2023-05-23 06:53:53,209: INFO/MainProcess] Task app.stream_processing.record_stream[fdfc459f-9c70-4c8a-928b-1bc81076f3ea] received
birdcage-birdcage_backend-1   | [2023-05-23 06:53:53,225: INFO/MainProcess] Task app.stream_processing.analyze_recordings[7d9c8ed6-d884-4f5c-b916-58d566c40b8c] received
birdcage-birdcage_backend-1   | [2023-05-23 06:54:08,405: WARNING/ForkPoolWorker-1] Recording successful. File saved to: /app/../tmp/01dc7e2d0d2c4d22be7cd6d61a599a60.wav
birdcage-birdcage_backend-1   | [2023-05-23 06:54:24,629: WARNING/ForkPoolWorker-1] Recording successful. File saved to: /app/../tmp/c40c82589b4a4cc4b1da690c8b22d389.wav
birdcage-birdcage_backend-1   | [2023-05-23 06:54:40,981: WARNING/ForkPoolWorker-1] Recording successful. File saved to: /app/../tmp/1611058f51eb4307837829a51cb5410b.wav
birdcage-birdcage_backend-1   | [2023-05-23 06:54:57,151: WARNING/ForkPoolWorker-1] Recording successful. File saved to: /app/../tmp/6c806fdd70914f2faa912fe54e1455ce.wav
birdcage-birdcage_backend-1   | [2023-05-23 06:55:13,367: WARNING/ForkPoolWorker-1] Recording successful. File saved to: /app/../tmp/f99913c16d204fd38bf4af21874e7bde.wav
birdcage-birdcage_backend-1   | av_interleaved_write_frame(): No space left on device
birdcage-birdcage_backend-1   | Error writing trailer of /app/../tmp/29c32bb919c94d548f418ce37d311eb0.wav: No space left on device
birdcage-birdcage_backend-1   | [2023-05-23 06:55:26,827: WARNING/ForkPoolWorker-1] Error: ffmpeg error (see stderr output for detail)
birdcage-birdcage_backend-1   | [2023-05-23 06:55:26,827: WARNING/ForkPoolWorker-1] Recording failed. Error: ffmpeg error (see stderr output for detail)

```

Clearly I have plenty of space. Odd!
```
[root@homedocker1 ~]# df -h
Filesystem                       Size  Used Avail Use% Mounted on
devtmpfs                         2.0G     0  2.0G   0% /dev
tmpfs                            2.0G     0  2.0G   0% /dev/shm
tmpfs                            2.0G   18M  2.0G   1% /run
tmpfs                            2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/mapper/centos-root          150G   60G   91G  40% /
/dev/mapper/centos-home           42G  1.3G   40G   3% /home
/dev/sda1                       1014M  156M  859M  16% /boot
overlay                          150G   60G   91G  40% /var/lib/docker/overlay2/b811da5f34bbbcba628e46a87b25df3a16e808fcea8ab3887b948b98f5e4f269/merged
overlay                          150G   60G   91G  40% /var/lib/docker/overlay2/f6488296b205ad41f22d44dddda125dac660c90a3df79589ba00e617849f0682/merged
overlay                          150G   60G   91G  40% /var/lib/docker/overlay2/a9ba92bc3f9911070240b4b0d7457f9e1cfe1c4add8ab7ca621b2914f42f82fb/merged
overlay                          150G   60G   91G  40% /var/lib/docker/overlay2/900782b1e17c2cbdbc733c4130171e2796cec3b91bfb73daba099192b356339d/merged
tmpfs                            396M     0  396M   0% /run/user/0
overlay                          150G   60G   91G  40% /var/lib/docker/overlay2/6c44a375c3f726a495f9af742aa70777ea7eab7806381b6179f8cabd5a574feb/merged
overlay                          150G   60G   91G  40% /var/lib/docker/overlay2/6b10720f7bc30a4058181c7fe6fa808cf2597431ecc67119d20426de83e0eee7/merged
overlay                          150G   60G   91G  40% /var/lib/docker/overlay2/e25837eb93c2babadc836add6be8d6479c39897e4e8c2f54c73e5a0b7f62ce73/merged
overlay                          150G   60G   91G  40% /var/lib/docker/overlay2/604448a1ad41468051a055f5610fb843e14e23f8c9aa78b2a2721dcd73c5a852/merged
```

**Comment by Phaeton** [comment]
If you `docker exec -it birdcage_backend bash` into the server and run `du -sh tmp`, how big is that folder? Is birdnetserver running? Your log shows multiple writes to `/tmp`, but does not show the analysis requests. I would guess birdnetserver is down or you need to increase the `tmpfs:` size. 16M may be too small, see the line comment in the `docker-compose.yml`.

**Comment by yetdog** [comment]
> If you `docker exec -it birdcage_backend bash` into the server and run `du -sh tmp`, how big is that folder? Is birdnetserver running? Your log shows multiple writes to `/tmp`, but does not show the analysis requests. I would guess birdnetserver is down or you need to increase the `tmpfs:` size. 16M may be too small, see the line comment in the `docker-compose.yml`.

Appreciate all your help on this!

I did a docker system prune and then also added in a volume mapping for ./tmp -> /tmp (like your fork), and it seemed to stop erroring on space.

However, you're correct that there are no log entries for analysis, and subsequently, nothing showing up in the UI for detections. birdnetserver is running (I think?):

```
[root@homedocker1 birdcage]# docker logs birdnet-analyzer_birdnetserver_1
UP AND RUNNING! LISTENING ON 0.0.0.0:8080
UP AND RUNNING! LISTENING ON 0.0.0.0:8080
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
```

The logs I've provided have all been from the attached output of docker compose up, for what it's worth. Would the analysis lines show up there?

**Comment by yetdog** [comment]
And I ran out of space again, this time after far more recordings. tmpfs raised to 64MB this time. I'm guessing what's happening is, the recordings are being made, but not analyzed, so the raw recordings are never being rotated out and *whatever* the size of tmpfs is, will eventually be exhausted. 

I see the initial task created to loop through the recordings:
```
birdcage-birdcage_backend-1   | [2023-05-23 06:53:53,225: INFO/MainProcess] Task app.stream_processing.analyze_recordings[7d9c8ed6-d884-4f5c-b916-58d566c40b8c] received
```
But can't seem to find where it's falling over. 

I wonder... is config.py, at the root of the birdcage_backend container in use? Because It's still leveraging that 192.168.1.75 address...hmmm

```
root@1ae0ba7a08ed:/app# cat /config.py 
import os

DATABASE_FILE = os.environ.get('DATABASE_FILE', 'birdcage.db')
API_SERVER_PORT = int(os.environ.get('API_SERVER_PORT', 7006))
TEMP_DIR_NAME = os.environ.get('TEMP_DIR_NAME', 'tmp')
ANALYZE_SERVER = os.environ.get('ANALYZE_SERVER', '192.168.1.75')
ANALYZE_PORT = int(os.environ.get('ANALYZE_PORT', 7667))
DETECTION_DIR_NAME = os.environ.get('DETECTION_DIR_NAME', 'detections')
CORS_ORIGINS = os.environ.get('CORS_ORIGINS', 'http://192.168.1.75:7009')
REDIS_SERVER = os.environ.get('REDIS_SERVER', '192.168.1.75')
REDIS_PORT = os.environ.get('REDIS_PORT', 6380)
```

**Comment by Phaeton** [comment]
> I did a docker system prune and then also added in a volume mapping for ./tmp -> /tmp (like your fork), and it seemed to stop erroring on space.

You will eventually want to unwind this. You must have been looking at my unpatched main branch. Long term you do not want to be writing the temporary data to disk. You are running out of space as the files are not being analyzed and removed. And it does not take long to fill up a 16mb buffer...

> 
> However, you're correct that there are no log entries for analysis, and subsequently, nothing showing up in the UI for detections. birdnetserver is running (I think?):
> 
> ```
> [root@homedocker1 birdcage]# docker logs birdnet-analyzer_birdnetserver_1
> UP AND RUNNING! LISTENING ON 0.0.0.0:8080
> UP AND RUNNING! LISTENING ON 0.0.0.0:8080
> INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
> ```
I agree, looks like the analysis server is up. But the data is not making it to the analysis server. You sure you got things mapped in your `docker-compose.yml` correctly? Correct paths and ports? You should be seeing activity in both birdnetserver and birdcage_backend.

**Comment by Phaeton** [comment]
Everything looks OK to me in that screenshot. You able to publish a snip of your `docker-compose.yml` that includes all 4 containers? The thing I would guess without seeing it all would be that your birdnetserver container is in a different network than your other 3. Make sure all 4 containers are in the same one.

**Comment by mmcc-xx** [comment]
FYI: The values in config.py are overridden by environment variables set in the docker-compose file. I have the defaults set to values that work in my test environment. 

Start with getting the birdnet-analyzer service running. If it is working correctly, you should be able to do a wget from the command line of your server to http://(analyzer ip address):(analyzer port)/healthcheck and get back a json string like {"msg": "Server is healthy."}

Once you have that working, put that IP address and port into the docker compose file for ANALYZE_SERVER and ANALYZE_PORT.

Feel free to share your whole docker-compose file. We'll get it going I have no doubt.

Later today I'll push up an image of the analyzer so you can avoid that step. If and when the BirdNET folks start providing images themselves I'll switch.

**Comment by yetdog** [comment]
I just added the birdnetserver container to the docker compose. I suspect the networking is acting as an isolating factor between your app, and the birdnetserver:

```
[root@homedocker1 birdcage]# cat docker-compose.yml 
version: '3.8'

services:
  birdnetserver:
    restart: unless-stopped
    image: birdnetserver
    ports:
      - 7667:8080
    networks:
     - birdcage_net
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - birdcage_net

  birdcage_backend:
    image: "mmcc73/birdcage_backend:latest"
    ports:
      - "7007:7007"
    environment:
      DATABASE_FILE: /db/birdcage.db
      API_SERVER_PORT: 7007
      TEMP_DIR_NAME: tmp
      ANALYZE_SERVER: 192.168.111.170
      ANALYZE_PORT: 7667
      DETECTION_DIR_NAME: detections
      CORS_ORIGINS: http://192.168.111.170:7008
      REDIS_SERVER: redis
      REDIS_PORT: 6379
    tmpfs:
      - /tmp:size=64M #you might want to increase this size if you are recording a bunch of streams, if you streams are particularly hi-res, or if your analyzer might be periodically unavailable
    volumes:
      - "./detections:/detections"
      - "./db:/db"
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/matt/birdcage/timezone:/etc/timezone:ro"
    depends_on:
      - redis
    networks:
      - birdcage_net

  birdcage_frontend:
    image: "mmcc73/birdcage_frontend:latest"
    ports:
      - "7008:7008"
    environment:
      API_SERVER_URL: http://192.168.111.170:7007
      WEBUI_PORT: 7008
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/matt/birdcage/timezone:/etc/timezone:ro"
    depends_on:
      - birdcage_backend
    networks:
      - birdcage_net

networks:
  birdcage_net:
    driver: host
```

Note I changed the driver from bridge to host. This doesn't seem to have made a difference either way. Of note, if I play with the port number for ANALYZE_PORT, I get a hard failure during docker compose up:
```
birdcage-birdcage_backend-1   | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.111.170', port=8080): Max retries exceeded with url: /predictedspecies?latitude=35.86264&longitude=-86.66016&week_number=21&sf_thresh=0.03 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1efdfa1d20>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

So I would assume that the absence of this error means it is connecting successfully / can see the server. So...yeah. I'm confused. :)
